# se repite el contenido existente en application.properties 
guru:
  jms:
    username: JMS Username
    password: somepass
    url: SomeUrl
# --- actua de separador interesante para introducir diferentes 
# configuraciones en el mismo archivo
---
spring:
    profiles: de
guru:
  jms:
    username: JMS Username $$$$$$ German
